### ISSUE TITLE
"Cannot read property 'doAction' of undefined" error

### ISSUE THREAD

**Issue by koesbong** [dominique-mueller/angular2-notifier#1] opened 2016-07-14 20:28 UTC
#### I am submitting a ...

```
[x] Bug report
[ ] Feature request
[ ] Support
[ ] Other
```

I am getting the `Cannot read property 'doAction' of undefined` error when trying to show a success notification. Here is a snippet of relevant code:

```
import { Component, OnInit, Input } from '@angular/core';
import { Router }           from '@angular/router';
import { Http, Headers } from '@angular/http';

import { User }        from '../user';
import { Workbook }        from '../workbook';
import { OrbitService } from '../orbit.service';
import { View }        from '../view';
import { NotifierService } from 'angular2-notifier';

export class ViewsComponent implements OnInit {
  user: User;
  myViews: View[];

  constructor(
    private notifier: NotifierService,
    private router: Router,
    private orbitService: OrbitService) {}

  getPptx() {
    this.orbitService.getPptx(this.selectedImg, this.user)
      .then(response => {
        console.log(this.notifier.success);
        this.notifier.success(response.downloadPath);
      });
  }
```

Doing a log on `this.notifier.success` shows the right method being returned. The issue seems to be in `notifier.service.ts` where `this.notifierContainer` is `undefined`:

```
public notify( type: string, message: string ): Promise<any> {
  return this.notifierContainer.doAction( {
  payload: new NotifierNotification( type, message ),
  type: SHOW
  } );
}
```

Is there something that I am not doing right?
#### Environment

| Component | Details |
| --- | --- |
| Version of Angular 2 | 2.0.0-rc.4 |
| Version of angular2-notifier | 0.2.0 |
| Browser(s) | [ Chrome] |

**Comment by itsdevdom** [comment] 2016-07-14 22:36
Ok, so after investigating the issue further, I found that the routing produces this issue. I've actually never tested the library in combination with routing.

And (luckily) I have a pretty good idea on how to fix this! I'm going to implement as quickly as possible.

**Comment by itsdevdom** [comment] 2016-07-14 23:23
Ok, fixed with commit 84d4e0c591950bd48755d8e826704da61fe90adf, new version **[0.2.1](https://github.com/dominique-mueller/angular2-notifier/releases/tag/0.2.1)** is up on NPM. Could you please update this dependency and check if it works for you now?

**Comment by koesbong** [comment] 2016-07-15 01:30
@dominique-mueller Thanks! I see the notification but also noticed this in the console

![image](https://cloud.githubusercontent.com/assets/107074/16860920/09582dee-49f1-11e6-92fc-e3053258c779.png)

**Comment by itsdevdom** [comment] 2016-07-15 07:43
This seems to be an issue concerning animations. The latest version of Chrome should actually support the Web Animations API, at least my version (51) does.

If you are using the Web Animations API polyfill, don't use

``` html
<script src="https://npmcdn.com/web-animations-js/web-animations.min.js"></script>
```

but instead use

``` html
<script src="https://npmcdn.com/web-animations-js/web-animations-next.min.js"></script>
```

And remember to put it before everything else is loaded.

**Comment by koesbong** [comment] 2016-07-15 17:19
@dominique-mueller weird, I do have Chrome 51. I am not using the web animations API at all, but let me see if loading the web animations polyfill will work.

**Comment by koesbong** [comment] 2016-07-15 17:24
@dominique-mueller even weirder, when I added the web animations API script, the error in the console went away, but notifier never showed up.  :-/

**Comment by itsdevdom** [comment] 2016-07-15 18:35
Hm, that actually is weird. I'm using the Web Animations API within the library, so every browser - except the newer versions of Chrome and the next version of Firefox - needs this polyfill. It seems that the Promise of `element.animate().finished` doesn't get returned properly, but I am not able to reproduce your error.

Could you maybe create a Plunker or similar that reproduces this issue? For now, disabling the animations in the notifier options may possibly be a workaround. Details about this option are in the README.

**Comment by itsdevdom** [comment] 2016-12-04 17:47
There is an all new version of this library, available under [https://github.com/dominique-mueller/angular-notifier](https://github.com/dominique-mueller/angular-notifier). For details, read [https://github.com/dominique-mueller/angular2-notifier/issues/2](https://github.com/dominique-mueller/angular2-notifier/issues/2).

If this problem should occur again, just simply open up a new issue within the new repository.

**Closed as completed by itsdevdom** 2016-12-04 17:47 UTC
Labels: prio 3: required, component: animations, need: repro
